version: "3.8"

services:
  db:
    build:
      context: ./db
    container_name: lockguard_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: iot
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - lockguard_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lockguard_backend
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=iot
      - PORT=5000
      - EMAIL_USER=nphlinh23@clc.fitus.edu.vn
      - EMAIL_PASS=gipi grxc hswg pxoj
      - MQTT_BROKER_URL=mqtt://broker.hivemq.com:1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - PUBLIC_URL=https://3a7f80bb9757.ngrok-free.app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - lockguard_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lockguard_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - lockguard_network
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - lockguard_network

networks:
  lockguard_network:
    driver: bridge
