CREATE DATABASE iot;

USE iot;

CREATE TABLE pir_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  value BOOLEAN
);

CREATE TABLE password_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  value BOOLEAN
);
