CREATE DATABASE IF NOT EXISTS iot;
USE iot;

CREATE TABLE IF NOT EXISTS pir_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  value BOOLEAN
);

CREATE TABLE IF NOT EXISTS password_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  value BOOLEAN
);

INSERT INTO pir_logs (value) VALUES (1), (0), (1);
INSERT INTO password_logs (value) VALUES (1), (0), (1);
